# Make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'pylode-to-pages'
description: 'converts ontology descriptions into html by using pylode'
branding: # Look at documentation for branding options/requirements. These are my favorites.
  icon: 'refresh-cw'
  color: 'blue'
inputs:
  baseurl:
    description: 'urlbase of the domain where this ontology gets published.'
    required: true
  logconf:
    description: 'Log conf file in yml'
    required: false
    default: 'logconf.yml'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.baseurl }}
    - ${{ inputs.logconf }}
